/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesStructuralRouteImport } from './routes/services.structural'
import { Route as ServicesProjectManagementRouteImport } from './routes/services.project-management'
import { Route as ServicesMarineRouteImport } from './routes/services.marine'
import { Route as ServicesHydraulicRouteImport } from './routes/services.hydraulic'
import { Route as ServicesFacadeRouteImport } from './routes/services.facade'
import { Route as ServicesExpertReportsRouteImport } from './routes/services.expert-reports'
import { Route as ServicesCivilRouteImport } from './routes/services.civil'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStructuralRoute = ServicesStructuralRouteImport.update({
  id: '/services/structural',
  path: '/services/structural',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProjectManagementRoute =
  ServicesProjectManagementRouteImport.update({
    id: '/services/project-management',
    path: '/services/project-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMarineRoute = ServicesMarineRouteImport.update({
  id: '/services/marine',
  path: '/services/marine',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHydraulicRoute = ServicesHydraulicRouteImport.update({
  id: '/services/hydraulic',
  path: '/services/hydraulic',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFacadeRoute = ServicesFacadeRouteImport.update({
  id: '/services/facade',
  path: '/services/facade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExpertReportsRoute = ServicesExpertReportsRouteImport.update({
  id: '/services/expert-reports',
  path: '/services/expert-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCivilRoute = ServicesCivilRouteImport.update({
  id: '/services/civil',
  path: '/services/civil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/projects': typeof ProjectsRoute
  '/services/civil': typeof ServicesCivilRoute
  '/services/expert-reports': typeof ServicesExpertReportsRoute
  '/services/facade': typeof ServicesFacadeRoute
  '/services/hydraulic': typeof ServicesHydraulicRoute
  '/services/marine': typeof ServicesMarineRoute
  '/services/project-management': typeof ServicesProjectManagementRoute
  '/services/structural': typeof ServicesStructuralRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/projects': typeof ProjectsRoute
  '/services/civil': typeof ServicesCivilRoute
  '/services/expert-reports': typeof ServicesExpertReportsRoute
  '/services/facade': typeof ServicesFacadeRoute
  '/services/hydraulic': typeof ServicesHydraulicRoute
  '/services/marine': typeof ServicesMarineRoute
  '/services/project-management': typeof ServicesProjectManagementRoute
  '/services/structural': typeof ServicesStructuralRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/projects': typeof ProjectsRoute
  '/services/civil': typeof ServicesCivilRoute
  '/services/expert-reports': typeof ServicesExpertReportsRoute
  '/services/facade': typeof ServicesFacadeRoute
  '/services/hydraulic': typeof ServicesHydraulicRoute
  '/services/marine': typeof ServicesMarineRoute
  '/services/project-management': typeof ServicesProjectManagementRoute
  '/services/structural': typeof ServicesStructuralRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/projects'
    | '/services/civil'
    | '/services/expert-reports'
    | '/services/facade'
    | '/services/hydraulic'
    | '/services/marine'
    | '/services/project-management'
    | '/services/structural'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/projects'
    | '/services/civil'
    | '/services/expert-reports'
    | '/services/facade'
    | '/services/hydraulic'
    | '/services/marine'
    | '/services/project-management'
    | '/services/structural'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/projects'
    | '/services/civil'
    | '/services/expert-reports'
    | '/services/facade'
    | '/services/hydraulic'
    | '/services/marine'
    | '/services/project-management'
    | '/services/structural'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesCivilRoute: typeof ServicesCivilRoute
  ServicesExpertReportsRoute: typeof ServicesExpertReportsRoute
  ServicesFacadeRoute: typeof ServicesFacadeRoute
  ServicesHydraulicRoute: typeof ServicesHydraulicRoute
  ServicesMarineRoute: typeof ServicesMarineRoute
  ServicesProjectManagementRoute: typeof ServicesProjectManagementRoute
  ServicesStructuralRoute: typeof ServicesStructuralRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/structural': {
      id: '/services/structural'
      path: '/services/structural'
      fullPath: '/services/structural'
      preLoaderRoute: typeof ServicesStructuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/project-management': {
      id: '/services/project-management'
      path: '/services/project-management'
      fullPath: '/services/project-management'
      preLoaderRoute: typeof ServicesProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marine': {
      id: '/services/marine'
      path: '/services/marine'
      fullPath: '/services/marine'
      preLoaderRoute: typeof ServicesMarineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hydraulic': {
      id: '/services/hydraulic'
      path: '/services/hydraulic'
      fullPath: '/services/hydraulic'
      preLoaderRoute: typeof ServicesHydraulicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/facade': {
      id: '/services/facade'
      path: '/services/facade'
      fullPath: '/services/facade'
      preLoaderRoute: typeof ServicesFacadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/expert-reports': {
      id: '/services/expert-reports'
      path: '/services/expert-reports'
      fullPath: '/services/expert-reports'
      preLoaderRoute: typeof ServicesExpertReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/civil': {
      id: '/services/civil'
      path: '/services/civil'
      fullPath: '/services/civil'
      preLoaderRoute: typeof ServicesCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesCivilRoute: ServicesCivilRoute,
  ServicesExpertReportsRoute: ServicesExpertReportsRoute,
  ServicesFacadeRoute: ServicesFacadeRoute,
  ServicesHydraulicRoute: ServicesHydraulicRoute,
  ServicesMarineRoute: ServicesMarineRoute,
  ServicesProjectManagementRoute: ServicesProjectManagementRoute,
  ServicesStructuralRoute: ServicesStructuralRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
